# Generated by Django 4.2 on 2025-02-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_newsitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='slug',
        ),
    ]
