# Generated by Django 4.2 on 2025-02-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newsitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
